version: '3.9'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: spectra-api
    restart: unless-stopped
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=ms_spectra
    ports:
      - "8000:8000"

volumes:
  qdrant_storage:
    driver: local


